language: android
script: "./gradlew build"
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-23

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-x86-android-22

    # Emulator Management: Create, Start and Wait
#    before_script:
#    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#    - emulator -avd test -no-skin -no-audio -no-window &
#    - curl http://is.gd/android_wait_for_emulator > android-wait-for-emulator
#    - chmod u+x android-wait-for-emulator
#    - ./android-wait-for-emulator
#    - adb shell input keyevent 82 &
